### PR TITLE
Refactor Browse Page and add a second line to city page

### PR DESCRIPTION
**Pull request by florianwittmann**
Second line of city page is now vegtype. As vegtype is now indicated by color, we could use second type for infos like todays opening hours or cousins / start with the short description or something other useful.

### CODE REVIEW

**Comment by bluszcz** [comment]
Thanks for another great pull request - change is stunning :dancers:

**Comment by florianwittmann** [comment]
Glad you like it :-)

**Comment by bluszcz** [comment]
I am thinking about making 'Veggie Sailing' hackathons - meeting in veggie cafe, eating, coding and writing reviews to improve database ;)

**Comment by florianwittmann** [comment]
Cool idea! Let's continue to improve the app until most stuff is functional and beautiful and then we can ask for database love.
Would you mind to add me for rights to issuetracker? Then I could selfasign me to a task for better coordination.

**Pull request merged**
