### PR TITLE
Implements #2: Filter by minimum vegType

### PR DESCRIPTION
**Pull request by florianwittmann**
Adds a pulleymenu entry to entries page which allows filtering based on veggie type.
When a filter is applied (for example 'vegetarian'), only entries at least vegetarian are shown.

### CODE REVIEW

**Comment by bluszcz** [comment]
Looks cool, thank you.

**Comment by bluszcz** [comment]
It would be cool to have colours (same like on entry list) when you choose the filter.

**Comment by florianwittmann** [comment]
Good idea. Will add colors for that too, yes.

**Comment by bluszcz** [comment]
Released: https://openrepos.net/content/bluszcz/veggie-sailor

**Pull request merged**
