### PR TITLE
Add translations and config

### PR DESCRIPTION
**Pull request by florianwittmann**
Adds translations config for transifex project: https://www.transifex.com/projects/p/veggiesailor

Update translations with transifex client tool: (working dir -> root project dir)

```
tx pull -a
lrelease translations/*.ts
```

### CODE REVIEW

**Comment by bluszcz** [comment]
Is there any source for harbour-veggiesailor-fr.qm? If yes - could it be attached?

Right now if someone would like to change French / German translation - cannot use project sources but has to use Transifex?

**Comment by bluszcz** [comment]
For example - why not keep in repo files like https://www.transifex.com/projects/p/veggiesailor/resource/VeggieSailor/l/de/download/for_use/ ?

**Comment by florianwittmann** [comment]
The source .ts file has not changed, it is still the same like in master, that's why it is not in changelog of the pull request ;-) But it is still there - sure.

The mentioned script will manage all languages automatically, pulls updated translation source files and generate the release qm.

**Comment by bluszcz** [comment]
Ok, I will check how does it work now.

As a developer of open source software - I want to have a possibility to edit translations using plain text files without 3rd party proprietary services - so checking now flow with Transifex.

**Comment by bluszcz** [comment]
After setting correctly authentication file and use provided config I am getting:

```
bluszcz@taller /tmp/VeggieSailor 
$ tx pull -a
Exception: Not Found
bluszcz@taller /tmp/VeggieSailor 
$ 
```

**Comment by bluszcz** [comment]
@florianwittmann In next days I won't have more time to spend for Transifex, can you prepare a a pull request with translated source files, please? This one seems to have only binaries and needs Transifex account to fetch current updated translated sources.

**Comment by bluszcz** [comment]
Checked on another computer in  hope to get all sources etc but still getting same error:

```
$ tx pull -a
Exception: Not Found
```

**Comment by bluszcz** [comment]
I  have just removed  old *ts files here: https://github.com/VeggieSailor/VeggieSailor/commit/cfd02cdf4ea7000cc38292806bd8c32d17e5b75a - thanks for pointing this out.

**Comment by florianwittmann** [comment]
You need tx client first. As explained this does INCLUDE the source files. They are just not listed in changes, because ... WELL they didn't change

**Comment by florianwittmann** [comment]
Client install tx client: http://docs.transifex.com/developer/client/setup

**Comment by bluszcz** [comment]
Florian, 

1) What do  you mean by "client install tx client"? 

I posted you output from this command on my two workstation - which I think means that I have installed it? Please correct me if I am missing something. Client is installed and authenticating. 

2) Files fr.ts and de.ts DID CHANGE: https://www.transifex.com/projects/p/veggiesailor/resource/VeggieSailor/l/fr/download/for_translation/ 

I would to have them updated in repo instead of providing config file for third party service to download them.

**Comment by bluszcz** [comment]
Command line command:

```
diff harbour-veggiesailor-de.ts /home/bluszcz/Downloads/for_use_veggiesailor_VeggieSailor_de.ts 
```

shows very nice what has been updated.

**Comment by florianwittmann** [comment]
Yes, because I translated AFTER making this pull request ;-) Just run my script once (You need transifex client first)

**Comment by bluszcz** [comment]
I think I wrote several times above, that I have installed it, and it does not work - and since it costed me too much time - I am done with it for now.

By myself I am going to stick with plain text translations / linguist. I have nothing against Transifex itself and if you want to translate there and commit back generated files / sources  - thats cool. Thank you.

**Comment by florianwittmann** [comment]
Sure, but therefore this branch still need to be merged ;-) The sources are still there, see https://github.com/florianwittmann/VeggieSailor/tree/translations/translations ...

**Comment by bluszcz** [comment]
I am getting slowly allergy to this tool ;)

I managed to make it work, kind of.

```
bluszcz@taller /tmp/clean/VeggieSailor 
$  /usr/local/bin/tx pull -a
Done.
bluszcz@taller /tmp/clean/VeggieSailor 
$ git status
On branch master
Your branch is ahead of 'origin/master' by 38 commits.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        translations/.tx/
        translations/VegSailor-de.qm
        translations/VegSailor.qm
```

ff you can and have time - please commit with corresponding tr files. Otherwise let's please close this thread. Thank you.

**Comment by florianwittmann** [comment]
Be sure to have the .transifexrc in your homedir:

```
[https://www.transifex.com]
hostname = https://www.transifex.com
password = YOURPASSWORD
token = 
username = YOURUSERNAME
```

But okay, I will make a new pull request with translations included.

**Comment by bluszcz** [comment]
1)

```
$ cat /home/bluszcz/.transifexrc 
[https://www.transifex.com]
hostname = https://www.transifex.com
password = 
token = 
username = bluszcz
```

2) 

Thank you.

**Comment by florianwittmann** [comment]
I see, just also run into problems now. Will look into it. It's working for all my other projects, but now for this one.

**Comment by bluszcz** [comment]
Heh, pitty :( This may explain my 'gegen die wand' with this.

Anyway:

1) I like the idea of nice web interface etc - but if it will be allowing full duplex - updating on web but also updating in repo directly and pushing to web.

As far as I see there are pull and push commands available, so it should be it ok (nobody should be forced to use web tool).

2) If there are 'binary' files like qm generated from source files - I will be always against commit only destination 'binary' file without full sources - which were missing in this case :)

Ping me please when you will manage make it work, I will rerun commands to see if it works... It could be really nice time saver - assuming that it will work finally, for me :+1:

**Pull request closed without merging**
